# Generated by Django 4.2.30 on 2026-07-15 07:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(blank=True, choices=[('brand_awareness', 'Brand Awareness'), ('product_launch', 'Product Launch'), ('event_promotion', 'Event Promotion'), ('retargeting', 'Retargeting')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('in_production', 'In Production'), ('live_pending_pop', 'Live Pending POP'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_locations', models.JSONField(default=list)),
                ('target_audience', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='creative_assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='creative_assets/thumbnails/')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], default='image', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('dimensions', models.JSONField(default=dict)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], default='pending', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creative_assets',
                'ordering': ['-created_at'],
            },
        ),
    ]
