# Generated by Django 4.2.16 on 2026-08-08 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('in_production', 'In Production'), ('live_pending_pop', 'Live Pending POP'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impressions', models.BigIntegerField(default=0)),
                ('clicks', models.BigIntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_locations', models.JSONField(default=list)),
                ('target_audience', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_objectives',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CreativeAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='creative_assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='creative_assets/thumbnails/')),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF')], default='image', max_length=20)),
                ('file_size', models.BigIntegerField(default=0)),
                ('dimensions', models.JSONField(default=dict)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'creative_assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TargetingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'targeting_methods',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('impressions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'targeting_regions',
                'ordering': ['order', 'name'],
            },
        ),
    ]
