# Generated by Django 4.2.16 on 2026-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
