# Generated by Django 4.2.16 on 2026-07-28 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaignmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creativeasset',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='creativeasset',
            name='rejection_reason',
        ),
    ]
