# Generated by Django 4.2.16 on 2026-07-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_creativeasset_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creativeasset',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
