# Generated by Django 4.2.16 on 2026-07-28 11:06

import uuid
from django.db import migrations, models
import django.db.models.deletion


# Seed data for CampaignObjective
OBJECTIVES = [
    {'code': 'route-targeting', 'label': 'Route Targeting', 'tag': 'A → B', 'description': 'Target assets moving between specific locations (A to B). Perfect for commuter corridors and transit routes.', 'order': 0},
    {'code': 'zone-targeting', 'label': 'Zone Targeting', 'tag': 'City Zones', 'description': 'Target assets operating within specific city boundaries or hubs — ideal for neighbourhood and district-level reach.', 'order': 1},
    {'code': 'fixed-spot-targeting', 'label': 'Fixed Spot Targeting', 'tag': 'Fixed Spots', 'description': 'Target assets at specific high-traffic coordinates — billboards, screens, and static placements at precise locations.', 'order': 2},
    {'code': 'pulse-targeting', 'label': 'Pulse Targeting', 'tag': 'Time Windows', 'description': 'Target high-density assets during specific time-windows or events. Surge your reach when it matters most.', 'order': 3},
    # Legacy codes from old CharField choices
    {'code': 'brand_awareness', 'label': 'Brand Awareness', 'tag': 'Awareness', 'description': 'Build broad awareness of your brand across multiple audiences and locations.', 'order': 4},
    {'code': 'product_launch', 'label': 'Product Launch', 'tag': 'Launch', 'description': 'Drive awareness and reach for a new product or service launch.', 'order': 5},
    {'code': 'event_promotion', 'label': 'Event Promotion', 'tag': 'Event', 'description': 'Promote an upcoming event and drive attendance through targeted placements.', 'order': 6},
    {'code': 'retargeting', 'label': 'Retargeting', 'tag': 'Retarget', 'description': 'Re-engage audiences who have previously interacted with your brand.', 'order': 7},
]


def seed_objectives_and_migrate(apps, schema_editor):
    CampaignObjective = apps.get_model('campaigns', 'CampaignObjective')
    # Seed all objectives
    obj_map = {}
    for data in OBJECTIVES:
        obj, _ = CampaignObjective.objects.get_or_create(code=data['code'], defaults=data)
        obj_map[data['code']] = obj


def reverse_seed(apps, schema_editor):
    # No reverse needed — just leave the objectives table
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_creativeasset_is_archived'),
    ]

    operations = [
        # 1. Create the taxonomy tables first
        migrations.CreateModel(
            name='CampaignObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'campaign_objectives',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TargetingMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'targeting_methods',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='TargetingRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('impressions', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'targeting_regions',
                'ordering': ['order', 'name'],
            },
        ),
        # 2. Seed objectives so they exist before the FK migration
        migrations.RunPython(seed_objectives_and_migrate, reverse_code=reverse_seed),
        # 3. Add a temporary FK column alongside the old char column
        migrations.AddField(
            model_name='campaign',
            name='objective_fk',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='campaigns.campaignobjective',
            ),
        ),
        # 4. Populate the new FK column from the old char column
        migrations.RunSQL(
            sql="""
                UPDATE campaigns
                SET objective_fk_id = (
                    SELECT id FROM campaign_objectives
                    WHERE code = campaigns.objective
                    LIMIT 1
                )
                WHERE campaigns.objective IS NOT NULL AND campaigns.objective != '';
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        # 5. Remove old char column
        migrations.RemoveField(model_name='campaign', name='objective'),
        # 6. Rename FK column to objective
        migrations.RenameField(model_name='campaign', old_name='objective_fk', new_name='objective'),
    ]
