# Generated by Django 4.2.16 on 2026-08-05 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_campaignobjective_targetingmethod_targetingregion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='campaigns.campaignobjective'),
        ),
    ]
