# Generated by Django 4.2.16 on 2026-07-21 10:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('JOB_PENDING_ACCEPT', 'Pending Acceptance'), ('JOB_PREP', 'Prep'), ('JOB_PRINTING', 'Printing'), ('JOB_QA', 'Quality Check'), ('JOB_SHIPPING', 'Shipping'), ('JOB_COMPLETED', 'Completed'), ('JOB_REROUTING', 'Rerouting'), ('JOB_STALLED', 'Stalled'), ('JOB_FORFEITED', 'Forfeited')], default='JOB_PENDING_ACCEPT', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('production_partner_source', models.CharField(choices=[('platform-assigned', 'Platform Assigned'), ('host-selected', 'Host Selected')], default='platform-assigned', max_length=30)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('checklist', models.JSONField(default=dict)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('accept_deadline', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reroute_count', models.IntegerField(default=0)),
                ('tried_production_partner_ids', models.JSONField(default=list)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='proof_of_play/')),
                ('proof_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'print_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
