# Generated by Django 4.2.16 on 2026-07-31 06:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pointofinterest'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxonomyNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'sort_order', 'label'],
            },
        ),
    ]
