# Generated by Django 4.2.16 on 2026-08-07 05:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_audiencebehavior_billingperiod_orientation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofOfPlayMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Proof of Play Methods',
                'ordering': ['sort_order', 'label'],
                'abstract': False,
            },
        ),
    ]
