# Generated by Django 4.2.16 on 2026-08-08 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('placements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payout',
            name='ad_placement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='placements.adplacement'),
        ),
    ]
