# Generated by Django 4.2.16 on 2026-07-24 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='paddle_subscription_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_intent_id',
            new_name='paddle_transaction_id',
        ),
        migrations.RenameField(
            model_name='payout',
            old_name='stripe_payout_id',
            new_name='paddle_payout_id',
        ),
    ]
