# Generated by Django 4.2.16 on 2026-07-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_stripe_charge_id_payment_paddle_subscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('processing', 'Processing'), ('in_transit', 'In Transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
