# Generated by Django 4.2.16 on 2026-07-22 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=255)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('lead_time', models.CharField(blank=True, max_length=50)),
                ('price_tier', models.CharField(default='$$', max_length=10)),
                ('specialties', models.JSONField(blank=True, default=list)),
                ('is_host_selectable', models.BooleanField(default=True)),
                ('is_platform_network', models.BooleanField(default=True)),
                ('production_lead_days', models.IntegerField(default=5)),
                ('shipping_days', models.IntegerField(default=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
