# Generated by Django 4.2.16 on 2026-07-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_otp_code_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarded_roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
