# Generated by Django 4.2.16 on 2026-07-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_managedaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reliability_score',
            field=models.IntegerField(default=100),
        ),
    ]
