# Generated by Django 4.2.16 on 2026-07-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_productionpartnerprofile_capacity_user_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='primary_goal',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
