# Generated by Django 4.2.16 on 2026-08-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_advertiserprofile_primary_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
