# Generated by Django 4.2.16 on 2026-08-03 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_google_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='monthly_budget',
        ),
        migrations.RemoveField(
            model_name='advertiserprofile',
            name='primary_goal',
        ),
        migrations.RemoveField(
            model_name='productionpartnerprofile',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='spaceownerprofile',
            name='number_of_spaces',
        ),
        migrations.RemoveField(
            model_name='user',
            name='company_size',
        ),
    ]
