# Generated by Django 4.2.16 on 2026-08-03 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companysize_industry_monthlybudget_primarygoal_and_more'),
        ('users', '0011_remove_advertiserprofile_industry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiserprofile',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.industry'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='monthly_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.monthlybudget'),
        ),
        migrations.AddField(
            model_name='advertiserprofile',
            name='primary_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.primarygoal'),
        ),
        migrations.AddField(
            model_name='productionpartnerprofile',
            name='capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.printercapacity'),
        ),
        migrations.AddField(
            model_name='spaceownerprofile',
            name='number_of_spaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.spacecount'),
        ),
        migrations.AddField(
            model_name='user',
            name='company_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.companysize'),
        ),
    ]
