# Generated by Django 4.2.16 on 2026-07-21 10:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('vehicles', 'Vehicles'), ('gadgets', 'Gadgets'), ('fixed', 'Fixed Spaces'), ('wearables', 'Wearables'), ('events', 'Events'), ('animals', 'Animals')], max_length=50)),
                ('item_type', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('min_dpi', models.IntegerField(default=300)),
                ('accepted_formats', models.JSONField(default=list)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='daily', max_length=20)),
                ('min_placement_duration', models.IntegerField(default=1)),
                ('bulk_discount_enabled', models.BooleanField(default=False)),
                ('bulk_discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fulfillment_type', models.CharField(choices=[('managed_printing', 'Managed Printing'), ('self_fulfillment', 'Self Fulfillment')], default='managed_printing', max_length=20)),
                ('self_fulfillment_reason', models.CharField(blank=True, max_length=50)),
                ('print_partner_routing', models.CharField(blank=True, max_length=20)),
                ('install_lead_days', models.IntegerField(default=2)),
                ('production_lead_days', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('available', 'Available'), ('occupied', 'Occupied'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('occupancy_rate', models.IntegerField(default=0)),
                ('impressions_estimate', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spaces',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpacePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='spaces/photos/')),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='spaces.space')),
            ],
            options={
                'db_table': 'space_photos',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SpaceAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('is_blocked', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='spaces.space')),
            ],
            options={
                'db_table': 'space_availability',
            },
        ),
    ]
