# Generated by Django 4.2.16 on 2026-08-08 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spaces', '0001_initial'),
        ('core', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='peak_exposures',
            field=models.ManyToManyField(blank=True, to='core.peakexposure'),
        ),
        migrations.AddField(
            model_name='space',
            name='preferred_production_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_for_spaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='space',
            name='traffic_densities',
            field=models.ManyToManyField(blank=True, to='core.trafficdensity'),
        ),
        migrations.AddField(
            model_name='space',
            name='usage_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usagetype'),
        ),
        migrations.AlterUniqueTogether(
            name='spaceavailability',
            unique_together={('space', 'date')},
        ),
    ]
