# Generated by Django 4.2.16 on 2026-08-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='audience_behaviors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='custom_period_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='designer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='space',
            name='end_point',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='space',
            name='orientation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='peak_exposures',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='physical_shape',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='primary_roads',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='space',
            name='proof_of_play_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='service_radius',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='space',
            name='traffic_densities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='space',
            name='usage_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='space',
            name='billing_period',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], default='daily', max_length=20),
        ),
    ]
