# Generated by Django 4.2.16 on 2026-08-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='external_partner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='space',
            name='external_partner_place_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
