# Generated by Django 4.2.16 on 2026-08-07 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_space_audience_behaviors_space_custom_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='facing_direction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='space',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='space',
            name='reference_photo',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/references/'),
        ),
    ]
