# Generated by Django 4.2.16 on 2026-08-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0003_space_external_partner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='external_partner_name',
        ),
        migrations.RemoveField(
            model_name='space',
            name='external_partner_place_id',
        ),
    ]
