# Generated by Django 4.2.16 on 2026-08-08 18:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ad_placement_confirmed', 'AdPlacement Confirmed'), ('ad_placement_cancelled', 'AdPlacement Cancelled'), ('payment_received', 'Payment Received'), ('payment_failed', 'Payment Failed'), ('campaign_active', 'Campaign Active'), ('campaign_completed', 'Campaign Completed'), ('job_accepted', 'Job Accepted'), ('job_completed', 'Job Completed'), ('message_received', 'Message Received'), ('review_received', 'Review Received'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved'), ('system', 'System')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
